Feature/exercicio 1
yasminmendes487/orion_bootcamp pull request #2
Opened 2023-10-10 01:00 UTC by yasminmendes487

2023-10-10 13:46 UTC, samuelcamilocosta requested changes

2023-10-10 13:46 UTC, samuelcamilocosta commented on exercicio1.ts
> +function contarVogais(palavra: String): Number {
Utilize string, number em (minúsculo) para declarações de variáveis de texto simples.
Evite usar String, Number (maiúsculo) a menos que seja necessário para operações avançadas.

string/number são tipos primitivos, já String e Number são objetos embutidos de código em JavaScript.
Eles tem um uso diferente, normalmente se usam eles para fazer operações complexas relacionadas ao seu tipo, exemplo: Number.parseInt(10.2)

```
const numeroString: string = "10.2";
const numero: number = Number.parseInt(numeroString);
console.log(numero); // Saída: 10
```

2023-10-10 13:46 UTC, samuelcamilocosta commented on exercicio1.ts
> +  palavra = palavra.toLowerCase();
Como uma boa prática a se seguir, é preferível criar uma nova variável para receber o valor com toLowerCase aplicado do que sobrescrever o parâmetro recebido na função

2023-10-10 13:46 UTC, samuelcamilocosta commented on exercicio1.ts
> +  const vogais: String = "aeiou";
a variável vogais não está sendo utilizada na função

2023-10-10 13:46 UTC, samuelcamilocosta commented on exercicio1.ts
> +  const vogais = "aeiouAEIOU";
Como você utiliza o toLowerCase para tratamento do parâmetro de entrada, poderia utilizar apenas as vogais minúsculas para reduzir a quantidade de comparações necessárias

2023-10-10 13:46 UTC, samuelcamilocosta commented on exercicio1.ts
> +function contarVogais(palavra: String): Number {
Dê uma lida na documentação do TSDoc
https://tsdoc.org/
Utilize ele para documentar suas funções, se tiver dúvida, pode nos procurar

2023-10-10 20:15 UTC, yasminmendes487 commented on exercicio1.ts
> +function contarVogais(palavra: String): Number {
Entendi! Já foi feita a correção. . Eu to na duvida se implemento a correção por aqui msm. Ou corrijo no vscode faço todo aquele processo no git.

2023-10-10 20:18 UTC, yasminmendes487 commented on exercicio1.ts
> +  palavra = palavra.toLowerCase();
criei uma nova variável para armazenar a versão da palavra em letras minúsculas

2023-10-10 21:00 UTC, samuelcamilocosta commented on exercicio1.ts
> +function contarVogais(palavra: String): Number {
Corrigir no vscode, commitar e dar push.
Vejo que foi feito a atualização, acredito que conseguiu corretamente.

2023-10-10 21:07 UTC, yasminmendes487 commented on exercicio1.ts
> +function contarVogais(palavra: String): Number {
eu fiz  por aqui msm, mas a proximo eu já sei. vlw

2023-10-10 21:41 UTC, samuelcamilocosta requested changes

2023-10-10 21:41 UTC, samuelcamilocosta commented on exercicio1.ts
> +const vogaisForm = document.getElementById("vogaisForm")as HTMLFormElement;
Como não há ação envolvendo o vogaisForm, poderia remover ele, assim também não precisaria desabilitar a regra do eslint

2023-10-10 21:41 UTC, samuelcamilocosta commented on exercicio1.ts
> +const palavraInput = document.getElementById("palavraInput")as HTMLInputElement;
faltou um espaço em ")as HTMLInputElement"

2023-10-10 21:41 UTC, samuelcamilocosta commented on exercicio1.ts
> +function contarVogais(palavra: string): number {
A documentação da função com o TSDoc seria algo assim

```
  /**
   * (Nome da função)
   *
   * (Breve descrição da função)
   *
   * @param x - (Descrição do parâmetro)
   *
   * @returns (Descrição do retorno esperado)
   */
```
   
Tem mais algumas tags de referência na documentação, porém essas são as principais e que iremos cobrar a utilização. Segue o link de referência https://tsdoc.org/

2023-10-10 23:37 UTC, alan-rocha-newrizon commented on exercicio1.ts
> +function contarVogais(palavra: string): number {
@yasminmendes487 O padrão de documentação ainda não está seguindo o tsdoc.

no tsdoc colocamos `@param nome-do-parametro - descrição`

2023-10-10 23:47 UTC, alan-rocha-newrizon requested changes

2023-10-10 23:47 UTC, alan-rocha-newrizon commented on exercicio1.ts
> +
Remover espaço

2023-10-10 23:47 UTC, alan-rocha-newrizon commented on exercicio1.ts
> + * @param {string} palavra - A palavra da qual se deseja contar as vogais.
no tsdoc, não utilizamos o tipo de parâmetro na documentação

2023-10-11 23:00 UTC, alan-rocha-newrizon approved these changes

2023-10-11 23:13 UTC, merged