Feature/exercicio 2
yasminmendes487/orion_bootcamp pull request #3
Opened 2023-10-11 06:12 UTC by yasminmendes487

2023-10-12 03:55 UTC, samuelcamilocosta requested changes

2023-10-12 03:55 UTC, samuelcamilocosta commented on exercicio2.ts
> +  //e) Demonstre todas as funções com o paradigma funcional
As funções que você criou, elas correspondem ao método de paradigma imperativo.
São abordagens que utilizam um for convencional com instruções descritivas.

O paradigma funcional teria uma utilização de métodos funcionais, alguns muito comuns vistos são findIndex, find, filter, forEach, map, entre tantos outros.

Vou deixar um link que aborda um pouco sobre o tema
https://medium.com/tableless/entendendo-programa%C3%A7%C3%A3o-funcional-em-javascript-de-uma-vez-c676489be08b

2023-10-12 03:55 UTC, samuelcamilocosta commented on exercicio2.ts
> +//a) Crie uma função que retorne a bio do id passado
Sugestão: Para melhorar a indentação do seu código, sugiro deixar uma linha de espaçamento entre o comentário indicando o exercício e a documentação, também é uma prática bem aceita, deixar um espaçamento entre o comando "//" do comentário e o que vier adiante, "//  a)"

2023-10-12 03:55 UTC, samuelcamilocosta commented on exercicio2.ts
> +  // Inicia a variável "bio" como uma string vazia
Comentários em código são uma ferramenta valiosa para tornar o código mais legível e acessível, especialmente para outros desenvolvedores que possam trabalhar no mesmo projeto. No entanto, os comentários devem ser usados com moderação. Abusar deles pode poluir visualmente o código, tornando-o confuso e difícil de ler.

Os comentários adicionados nas linhas 62, 65, 69, 72 e 76 nessa função getBioById, mais poluem visualmente o seu código, do que agrega uma explicação importante. Sugiro que você remova-os, isso tornará seu código mais limpo e organizado. Aplique essas alterações nas suas outras funções desenvolvidas

2023-10-12 03:55 UTC, samuelcamilocosta commented on exercicio2.ts
> + * * Altera a biografia ou o nome de um cientista por ID.
comentou um * a mais na documentação aqui

2023-10-12 05:52 UTC, yasminmendes487 commented on exercicio2.ts
> +  //e) Demonstre todas as funções com o paradigma funcional
Entao no caso é pra fazer todas as funções com os métodos funcionais e em outro arquivo fazer com os métodos imperativo?

2023-10-13 22:09 UTC, alan-rocha-newrizon requested changes

2023-10-13 22:09 UTC, alan-rocha-newrizon commented on exercicio2-imperativo.ts
> +return bio;
corrigir identação

2023-10-13 22:16 UTC, alan-rocha-newrizon commented
@yasminmendes487 seu PR tem conflitos. precisa verificar isso também, se não, não conseguimos fazer o merge

2023-10-13 22:48 UTC, samuelcamilocosta requested changes

2023-10-13 22:48 UTC, samuelcamilocosta commented on exercicio2-imperativo.ts
> +}  return bio;
O return bio deve ficar antes da chave para o código funcionar corretamente.
Da forma como ele está não funcionou

2023-10-14 04:48 UTC, closed without merging